CREATE COLLECTION R_ALEKS;
GRANT USAGE ON SCHEMA R_ALEKS TO U_ALEKS2;
CREATE TABLE R_ALEKS.STUDENT AS (SELECT * FROM DB_BOOK.STUDENT) WITH DATA;
GRANT SELECT ON R_ALEKS.STUDENT TO U_ALEKS2;
CREATE TABLE R_ALEKS.USERID_TO_STUDENTID ( USERID VARCHAR(10) CCSID 1208, ID INT);
GRANT SELECT ON R_ALEKS.USERID_TO_STUDENTID TO U_ALEKS2;

SELECT * FROM R_ALEKS.STUDENT;
SELECT * FROM R_ALEKS.USERID_TO_STUDENTID;

INSERT INTO R_ALEKS.USERID_TO_STUDENTID VALUES('U_ALEKS2',66054); 
SELECT * FROM R_ALEKS.STUDENT WHERE DEPT_NAME = (SELECT ID FROM R_ALEKS.USERID_TO_STUDENTID a, R_ALEKS.STUDENT b WHERE a.ID = b.ID);

CALL RCAC.CREATE_PERMISSION(
    'R_ALEKS',
    'RCAC7',
    'STUDENT',
    'SESSION_USER NOT LIKE ''%2%''',
    'ENABLE');
CALL RCAC.ROWACCESS('R_ALEKS','STUDENT','ACTIVATE');

CREATE TABLE R_ALEKS.STUDENT_DEPT AS ( SELECT ID, DEPT_NAME FROM R_ALEKS.STUDENT) 
DATA INITIALLY IMMEDIATE REFRESH DEFERRED MAINTAINED BY USER;

REFRESH TABLE R_ALEKS.STUDENT_DEPT;

CALL RCAC.CREATE_PERMISSION(
    'R_ALEKS',
    'RCAC8',
    'STUDENT',
    'DEPT_NAME = (SELECT DEPT_NAME FROM STUDENT WHERE ID IN ( SELECT ID FROM R_ALEKS.USERID_TO_STUDENTID WHERE USERID = SESSION_USER ))',
    'ENABLE');

CALL RCAC.CREATE_MASK('R_ALEKS','R_ID', 'STUDENT',
    'ID',
    'WHEN (ID = (SELECT ID FROM R_ALEKS.USERID_TO_STUDENTID WHERE USERID = SESSION_USER)) THEN ID ELSE NULL
    END ', 'ENABLE'); 

CALL  RCAC.COLUMNACCESS('R_ALEKS','STUDENT','ACTIVATE'); 
REFRESH TABLE  R_ALEKS.STUDENT_DEPT; 

