set schema P_ALEKS;

CREATE TABLE COMPENSATION2 AS (SELECT * FROM COMPENSATION) WITH DATA;
Select * from COMPENSATION;
Select * from EMPLOYEE;

CREATE TABLE ORGANIZATION_GROUP AS (SELECT ORGANIZATION_GROUP_CODE, MAX(ORGANIZATION_GROUP) as ORGANIZATION_GROUP FROM COMPENSATION2 group by ORGANIZATION_GROUP_CODE) WITH DATA;
Select * from ORGANIZATION_GROUP;
CALL QSYS2.QCMDEXC('CHGJOB INQMSGRPY(*SYSRPYL)');
ALTER TABLE COMPENSATION2 DROP COLUMN ORGANIZATION_GROUP;


CREATE TABLE JOB_FAMILY AS (SELECT JOB_FAMILY_CODE, MAX(JOB_FAMILY) as JOB_FAMILY FROM COMPENSATION2 group by JOB_FAMILY_CODE) WITH DATA;
Select * from JOB_FAMILY;
CALL QSYS2.QCMDEXC('CHGJOB INQMSGRPY(*SYSRPYL)');
ALTER TABLE COMPENSATION2 DROP COLUMN JOB_FAMILY;


CREATE TABLE JOB AS (SELECT JOB_CODE, MAX(JOB) as JOB FROM COMPENSATION2 group by JOB_CODE) WITH DATA;
Select * from JOB;
CALL QSYS2.QCMDEXC('CHGJOB INQMSGRPY(*SYSRPYL)');
ALTER TABLE COMPENSATION2 DROP COLUMN JOB;


CREATE TABLE DEPARTMENT AS (SELECT DEPARTMENT_CODE, MAX(DEPARTMENT) as DEPARTMENT FROM COMPENSATION2 group by DEPARTMENT_CODE) WITH DATA;
Select * from DEPARTMENT;
CALL QSYS2.QCMDEXC('CHGJOB INQMSGRPY(*SYSRPYL)');
ALTER TABLE COMPENSATION2 DROP COLUMN DEPARTMENT;


CREATE TABLE UNION AS (SELECT UNION_CODE, MAX(UNION) as UNION FROM COMPENSATION2 group by UNION_CODE) WITH DATA;
Select * from UNION;
CALL QSYS2.QCMDEXC('CHGJOB INQMSGRPY(*SYSRPYL)');
ALTER TABLE COMPENSATION2 DROP COLUMN UNION;

CALL QSYS2.QCMDEXC('CHGJOB INQMSGRPY(*SYSRPYL)');
ALTER TABLE COMPENSATION2 DROP COLUMN TOTAL_SALARY;

CALL QSYS2.QCMDEXC('CHGJOB INQMSGRPY(*SYSRPYL)');
ALTER TABLE COMPENSATION2 DROP COLUMN TOTAL_BENEFITS;

CALL QSYS2.QCMDEXC('CHGJOB INQMSGRPY(*SYSRPYL)');
ALTER TABLE COMPENSATION2 DROP COLUMN TOTAL_COMPENSATION;


Select * from COMPENSATION2;

WITH X AS (
SELECT ORGANIZATION_GROUP_CODE, ORGANIZATION_GROUP from compensation2
group by ORGANIZATION_GROUP_CODE, ORGANIZATION_GROUP)
SELECT ORGANIZATION_GROUP_CODE, COUNT(*) C FROM X
GROUP BY ORGANIZATION_GROUP_CODE
ORDER BY C DESC;

WITH X AS (
SELECT ORGANIZATION_GROUP_CODE, JOB from compensation2
group by ORGANIZATION_GROUP_CODE, JOB)
SELECT ORGANIZATION_GROUP_CODE, COUNT(*) C FROM X
GROUP BY ORGANIZATION_GROUP_CODE
ORDER BY C DESC;

WITH X AS (
SELECT JOB_FAMILY_CODE, JOB_FAMILY from compensation2
group by JOB_FAMILY_CODE, JOB_FAMILY)
SELECT JOB_FAMILY_CODE, COUNT(*) C FROM X
GROUP BY JOB_FAMILY_CODE
ORDER BY C DESC;

SELECT * FROM COMPENSATION2 WHERE SALARIES + OVERTIME + OTHER_SALARIES <> TOTAL_SALARY;

RENAME COMPENSATION2 TO EMPLOYEE;

RENAME EMPLOYEE TO COMPENSATION2;

Drop table compensation2;
--------------------------------------------------------------------------

CREATE TABLE SPENDREV2 AS (SELECT * FROM SPENDREV) WITH DATA;
Select * from SPENDREV2;

WITH X AS (
SELECT ORGANIZATION_GROUP_CODE, ORGANIZATION_GROUP from SPENDREV2
group by ORGANIZATION_GROUP_CODE, ORGANIZATION_GROUP)
SELECT ORGANIZATION_GROUP_CODE, COUNT(*) C FROM X
GROUP BY ORGANIZATION_GROUP_CODE
ORDER BY C DESC;

CREATE TABLE ORGANIZATION_GROUP2 AS (SELECT ORGANIZATION_GROUP_CODE, MAX(ORGANIZATION_GROUP) as ORGANIZATION_GROUP FROM SPENDREV2 group by ORGANIZATION_GROUP_CODE) WITH DATA;
Select * from ORGANIZATION_GROUP2;
CALL QSYS2.QCMDEXC('CHGJOB INQMSGRPY(*SYSRPYL)');
ALTER TABLE SPENDREV2 DROP COLUMN ORGANIZATION_GROUP;

DROP table ORGANIZATION_GROUP2;

CREATE TABLE DEPARTMENT2 AS (SELECT DEPARTMENT_CODE, MAX(DEPARTMENT) as DEPARTMENT FROM SPENDREV2 group by DEPARTMENT_CODE) WITH DATA;
Select * from DEPARTMENT2;
CALL QSYS2.QCMDEXC('CHGJOB INQMSGRPY(*SYSRPYL)');
ALTER TABLE SPENDREV2 DROP COLUMN DEPARTMENT;

DROP table department2;

CREATE TABLE PROGRAM AS (SELECT PROGRAM_CODE, MAX(PROGRAM) as PROGRAM FROM SPENDREV2 group by PROGRAM_CODE) WITH DATA;
Select * from PROGRAM;
CALL QSYS2.QCMDEXC('CHGJOB INQMSGRPY(*SYSRPYL)');
ALTER TABLE SPENDREV2 DROP COLUMN PROGRAM;

CREATE TABLE CHARACTER AS (SELECT CHARACTER_CODE, MAX(CHARACTER) as CHARACTER FROM SPENDREV2 group by CHARACTER_CODE) WITH DATA;
Select * from CHARACTER;
CALL QSYS2.QCMDEXC('CHGJOB INQMSGRPY(*SYSRPYL)');
ALTER TABLE SPENDREV2 DROP COLUMN CHARACTER;

CREATE TABLE OBJECT AS (SELECT OBJECT_CODE, MAX(OBJECT) as OBJECT FROM SPENDREV2 group by OBJECT_CODE) WITH DATA;
Select * from OBJECT;
CALL QSYS2.QCMDEXC('CHGJOB INQMSGRPY(*SYSRPYL)');
ALTER TABLE SPENDREV2 DROP COLUMN OBJECT;

CREATE TABLE SUB_OBJECT AS (SELECT SUB_OBJECT_CODE, MAX(SUB_OBJECT) as SUB_OBJECT FROM SPENDREV2 group by SUB_OBJECT_CODE) WITH DATA;
Select * from SUB_OBJECT;
CALL QSYS2.QCMDEXC('CHGJOB INQMSGRPY(*SYSRPYL)');
ALTER TABLE SPENDREV2 DROP COLUMN SUB_OBJECT;


CREATE TABLE FUND_TYPE AS (SELECT FUND_TYPE_CODE, MAX(FUND_TYPE) as FUND_TYPE FROM SPENDREV2 group by FUND_TYPE_CODE) WITH DATA;
Select * from FUND_TYPE;
CALL QSYS2.QCMDEXC('CHGJOB INQMSGRPY(*SYSRPYL)');
ALTER TABLE SPENDREV2 DROP COLUMN FUND_TYPE;


CREATE TABLE FUND AS (SELECT FUND_CODE, MAX(FUND) as FUND FROM SPENDREV2 group by FUND_CODE) WITH DATA;
Select * from FUND;
CALL QSYS2.QCMDEXC('CHGJOB INQMSGRPY(*SYSRPYL)');
ALTER TABLE SPENDREV2 DROP COLUMN FUND;


CREATE TABLE FUND_CATEGORY AS (SELECT FUND_CATEGORY_CODE, MAX(FUND_CATEGORY) as FUND_CATEGORY FROM SPENDREV2 group by FUND_CATEGORY_CODE) WITH DATA;
Select * from FUND_CATEGORY;
CALL QSYS2.QCMDEXC('CHGJOB INQMSGRPY(*SYSRPYL)');
ALTER TABLE SPENDREV2 DROP COLUMN FUND_CATEGORY;

DROP TABLE SPENDREVRAW;



CREATE TABLE SPENDREVRAW AS (SELECT FUND FROM FUND RIGHT OUTER JOIN SPENDREV2
ON FUND.FUND_CODE = SPENDREV2.FUND_CODE) WITH DATA;
Select * from SPENDREVRAW;



CALL QSYS2.QCMDEXC('CHGJOB INQMSGRPY(*SYSRPYL)');
ALTER TABLE SPENDREV2 ADD COLUMN FUND Varchar(72);

UPDATE SPENDREV2 t1 INNER JOIN FUND t2 ON t1.FUND_CODE = t2.FUND_CODE SET t1.FUND = t2.FUND;

SELECT FUND.FUND, FUND_TYPE.FUND_TYPE,SUB_OBJECT.SUB_OBJECT
FROM SPENDREV2 INNER JOIN FUND ON SPENDREV2.FUND_CODE = FUND.FUND_CODE INNER JOIN FUND_TYPE ON SPENDREV2.FUND_TYPE_CODE = FUND_TYPE.FUND_TYPE_CODE INNER JOIN SUB_OBJECT ON SPENDREV2.SUB_OBJECT_CODE = SUB_OBJECT.SUB_OBJECT_CODE ;

SELECT FUND FROM FUND RIGHT OUTER JOIN SPENDREV2
ON FUND.FUND_CODE = SPENDREV2.FUND_CODE;

ALTER TABLE SPENDREVRAW ADD COLUMN FUND AS (SELECT FUND FROM FUND RIGHT OUTER JOIN SPENDREV2
ON FUND.FUND_CODE = SPENDREV2.FUND_CODE) WITH DATA;




SELECT FUND.FUND, SPENDREV2.* FROM FUND, SPENDREV2 WHERE FUND.FUND_CODE = SPENDREV2.FUND_CODE;

SELECT FUND.FUND FROM FUND, SPENDREV2 WHERE FUND.FUND_CODE = SPENDREV2.FUND_CODE;


drop table spendrevraw;

CREATE TABLE SPENDREVRAW AS (SELECT FISCAL_YEAR, RELATED_GOVT_UNITS,FUND,DEPARTMENT,PROGRAM,ORGANIZATION_GROUP,CHARACTER,OBJECT,SUB_OBJECT,FUND_TYPE,FUND_CATEGORY FROM SPENDREV2 
INNER JOIN FUND                 ON FUND.FUND_CODE                               = SPENDREV2.FUND_CODE 
INNER JOIN DEPARTMENT           ON DEPARTMENT.DEPARTMENT_CODE                   = SPENDREV2.DEPARTMENT_CODE 
INNER JOIN PROGRAM              ON PROGRAM.PROGRAM_CODE                         = SPENDREV2.PROGRAM_CODE
INNER JOIN ORGANIZATION_GROUP   ON ORGANIZATION_GROUP.ORGANIZATION_GROUP_CODE   = SPENDREV2.ORGANIZATION_GROUP_CODE 
INNER JOIN CHARACTER            ON CHARACTER.CHARACTER_CODE                     = SPENDREV2.CHARACTER_CODE 
INNER JOIN OBJECT               ON OBJECT.OBJECT_CODE                           = SPENDREV2.OBJECT_CODE 
INNER JOIN SUB_OBJECT           ON SUB_OBJECT.SUB_OBJECT_CODE                   = SPENDREV2.SUB_OBJECT_CODE 
INNER JOIN FUND_TYPE            ON FUND_TYPE.FUND_TYPE_CODE                     = SPENDREV2.FUND_TYPE_CODE 
INNER JOIN FUND_CATEGORY        ON FUND_CATEGORY.FUND_CATEGORY_CODE             = SPENDREV2.FUND_CATEGORY_CODE) WITH DATA;
Select * from SPENDREVRAW;

ALTER TABLE SPENDREVRAW ADD COLUMN FUND varchar(52),
                        ADD COLUMN DEPARTMENT varchar(52),
                        ADD COLUMN PROGRAM varchar(52),
                        ADD COLUMN ORGANIZATION_GROUP varchar(52),
                        ADD COLUMN HARACTER varchar(52),
                        ADD COLUMN OBJECT varchar(52),
                        ADD COLUMN SUB_OBJECT varchar(52),
                        ADD COLUMN FUND_TYPE varchar(52),
                        ADD COLUMN FUND_CATEGORY varchar(52);

ALTER TABLE SPENDREVRAW DROP COLUMN DEPARTMENT;



ALTER TABLE SPENDREVRAW ADD COLUMN DEPARTMENT varchar(52);
INSERT into SPENDREVRAW (DEPARTMENT) (SELECT DEPARTMENT.DEPARTMENT FROM DEPARTMENT, SPENDREV2 WHERE DEPARTMENT.DEPARTMENT_CODE = SPENDREV2.DEPARTMENT_CODE);
ALTER TABLE SPENDREVRAW ADD COLUMN OBJECT varchar(52);
INSERT into SPENDREVRAW (OBJECT) (SELECT OBJECT.OBJECT FROM OBJECT, SPENDREV2 WHERE OBJECT.OBJECT_CODE = SPENDREV2.OBJECT_CODE);

Select * from SPENDREVRAW;

ALTER TABLE SPENDREVRAW DROP COLUMN FUND;

INSERT into SPENDREVRAW (
SELECT FUND,DEPARTMENT,PROGRAM,ORGANIZATION_GROUP,CHARACTER,OBJECT,SUB_OBJECT,FUND_TYPE,FUND_CATEGORY FROM SPENDREVRAW 
INNER JOIN FUND                 ON FUND.FUND_CODE                               = SPENDREVRAW.FUND_CODE 
INNER JOIN DEPARTMENT           ON DEPARTMENT.DEPARTMENT_CODE                   = SPENDREVRAW.DEPARTMENT_CODE 
INNER JOIN PROGRAM              ON PROGRAM.PROGRAM_CODE                         = SPENDREVRAW.PROGRAM_CODE
INNER JOIN ORGANIZATION_GROUP   ON ORGANIZATION_GROUP.ORGANIZATION_GROUP_CODE   = SPENDREVRAW.ORGANIZATION_GROUP_CODE 
INNER JOIN CHARACTER            ON CHARACTER.CHARACTER_CODE                     = SPENDREVRAW.CHARACTER_CODE 
INNER JOIN OBJECT               ON OBJECT.OBJECT_CODE                           = SPENDREVRAW.OBJECT_CODE 
INNER JOIN SUB_OBJECT           ON SUB_OBJECT.SUB_OBJECT_CODE                   = SPENDREVRAW.SUB_OBJECT_CODE 
INNER JOIN FUND_TYPE            ON FUND_TYPE.FUND_TYPE_CODE                     = SPENDREVRAW.FUND_TYPE_CODE 
INNER JOIN FUND_CATEGORY        ON FUND_CATEGORY.FUND_CATEGORY_CODE             = SPENDREVRAW.FUND_CATEGORY_CODE);




SELECT DEPARTMENT.DEPARTMENT FROM DEPARTMENT, SPENDREV2 WHERE DEPARTMENT.DEPARTMENT_CODE = SPENDREV2.DEPARTMENT_CODE;

INSERT INTO SPENDREVRAW(DEPARTMENT) values (SELECT DEPARTMENT.DEPARTMENT FROM DEPARTMENT, SPENDREV2 WHERE DEPARTMENT.DEPARTMENT_CODE = SPENDREV2.DEPARTMENT_CODE);

SELECT DEPARTMENT.DEPARTMENT FROM DEPARTMENT, SPENDREV2 WHERE DEPARTMENT.DEPARTMENT_CODE = SPENDREV2.DEPARTMENT_CODE;

SELECT * INTO SPENDREVRAW FROM FUND, SPENDREV2 WHERE FUND.FUND_CODE = SPENDREV2.FUND_CODE;


SELECT * FROM SPENDREV2 
INNER JOIN FUND                 ON FUND.FUND_CODE                               = SPENDREV2.FUND_CODE 
INNER JOIN DEPARTMENT           ON DEPARTMENT.DEPARTMENT_CODE                   = SPENDREV2.DEPARTMENT_CODE 
INNER JOIN PROGRAM              ON PROGRAM.PROGRAM_CODE                         = SPENDREV2.PROGRAM_CODE
INNER JOIN ORGANIZATION_GROUP   ON ORGANIZATION_GROUP.ORGANIZATION_GROUP_CODE   = SPENDREV2.ORGANIZATION_GROUP_CODE 
INNER JOIN CHARACTER            ON CHARACTER.CHARACTER_CODE                     = SPENDREV2.CHARACTER_CODE 
INNER JOIN OBJECT               ON OBJECT.OBJECT_CODE                           = SPENDREV2.OBJECT_CODE 
INNER JOIN SUB_OBJECT           ON SUB_OBJECT.SUB_OBJECT_CODE                   = SPENDREV2.SUB_OBJECT_CODE 
INNER JOIN FUND_TYPE            ON FUND_TYPE.FUND_TYPE_CODE                     = SPENDREV2.FUND_TYPE_CODE 
INNER JOIN FUND_CATEGORY        ON FUND_CATEGORY.FUND_CATEGORY_CODE             = SPENDREV2.FUND_CATEGORY_CODE;



SELECT FISCAL_YEAR, RELATED_GOVT_UNITS,FUND,DEPARTMENT,PROGRAM,ORGANIZATION_GROUP,CHARACTER,OBJECT,SUB_OBJECT,FUND_TYPE,FUND_CATEGORY FROM SPENDREV2 
INNER JOIN FUND                 ON FUND.FUND_CODE                               = SPENDREV2.FUND_CODE 
INNER JOIN DEPARTMENT           ON DEPARTMENT.DEPARTMENT_CODE                   = SPENDREV2.DEPARTMENT_CODE 
INNER JOIN PROGRAM              ON PROGRAM.PROGRAM_CODE                         = SPENDREV2.PROGRAM_CODE
INNER JOIN ORGANIZATION_GROUP   ON ORGANIZATION_GROUP.ORGANIZATION_GROUP_CODE   = SPENDREV2.ORGANIZATION_GROUP_CODE 
INNER JOIN CHARACTER            ON CHARACTER.CHARACTER_CODE                     = SPENDREV2.CHARACTER_CODE 
INNER JOIN OBJECT               ON OBJECT.OBJECT_CODE                           = SPENDREV2.OBJECT_CODE 
INNER JOIN SUB_OBJECT           ON SUB_OBJECT.SUB_OBJECT_CODE                   = SPENDREV2.SUB_OBJECT_CODE 
INNER JOIN FUND_TYPE            ON FUND_TYPE.FUND_TYPE_CODE                     = SPENDREV2.FUND_TYPE_CODE 
INNER JOIN FUND_CATEGORY        ON FUND_CATEGORY.FUND_CATEGORY_CODE             = SPENDREV2.FUND_CATEGORY_CODE;
