use mydb;


USE `mydb` ;

CREATE TABLE IF NOT EXISTS ITEM (
  I_ID INT(11) NOT NULL,
  I_IM_ID INT(11) NOT NULL,
  I_NAME VARCHAR(24) NOT NULL,
  I_PRICE DECIMAL(5,2) NOT NULL,
  I_DATA VARCHAR(50) NOT NULL,
  PRIMARY KEY (I_ID));

CREATE TABLE IF NOT EXISTS WAREHOUSE (
  W_ID INT(11) NOT NULL,
  W_NAME VARCHAR(10) NOT NULL,
  W_STREET_1 VARCHAR(20) NOT NULL,
  W_CITY VARCHAR(20) NOT NULL,
  W_STATE CHAR(2) NOT NULL,
  W_ZIP CHAR(9) NOT NULL,
  W_TAX DECIMAL(4,4) NOT NULL,
  W_YTD DECIMAL(12,2) NOT NULL,
  PRIMARY KEY (W_ID));

CREATE TABLE IF NOT EXISTS DISTRICT (
  D_ID INT(11) NOT NULL,
  D_W_ID INT(11) NOT NULL,
  D_NAME VARCHAR(40) NOT NULL,
  D_STREET_1 VARCHAR(40) NOT NULL,
  D_STREET_2 VARCHAR(40) NOT NULL,
  D_CITY VARCHAR(40) NOT NULL,
  D_STATE VARCHAR(40) NOT NULL,
  D_ZIP VARCHAR(40) NOT NULL,
  D_TAX VARCHAR(40) NOT NULL,
  D_YTD VARCHAR(40) NOT NULL,
  D_NEXT_O_ID INT(11) NOT NULL,
  PRIMARY KEY (D_W_ID, D_ID),
  FOREIGN KEY (D_W_ID) REFERENCES WAREHOUSE(W_ID)
  );

CREATE TABLE IF NOT EXISTS CUSTOMER (
  C_ID INT(11) NOT NULL,
  C_D_ID INT(11) NOT NULL,
  C_W_ID INT(11) NOT NULL,
  C_FIRST VARCHAR(16) NOT NULL,
  C_MIDDLE CHAR(2) NOT NULL,
  C_LAST VARCHAR(16) NOT NULL,
  C_STREET_1 VARCHAR(20) NOT NULL,
  C_STREET_2 VARCHAR(20) NOT NULL,
  C_CITY VARCHAR(20) NOT NULL,
  C_STATE CHAR(2) NOT NULL,
  C_ZIP CHAR(9) NOT NULL,
  C_PHONE CHAR(16) NOT NULL,
  C_SINCE DATETIME NOT NULL,
  C_CREDIT CHAR(2) NOT NULL,
  C_CREDIT_LIM DECIMAL(12,2) NOT NULL,
  C_DISCOUNT DECIMAL(4,4) NOT NULL,
  C_BALANCE DECIMAL(12,2) NOT NULL,
  C_YTD_PAYMENT DECIMAL(12,2) NOT NULL,
  C_PAYMENT_CNT DECIMAL(4,0) NOT NULL,
  C_DELIVERY_CNT DECIMAL(4,0) NOT NULL,
  C_DATA VARCHAR(500) NOT NULL,
  PRIMARY KEY (C_W_ID, C_D_ID, C_ID),
  FOREIGN KEY (C_W_ID, C_D_ID) REFERENCES DISTRICT(D_W_ID,D_ID)
  );


CREATE TABLE IF NOT EXISTS `HISTORY` (
	H_C_ID INT(11) NOT NULL,
	H_C_D_ID INT(11) NOT NULL,
	H_C_W_ID INT(11) NOT NULL,
	H_D_ID INT(11) NOT NULL,
	H_W_ID INT(11) NOT NULL,
	H_DATE DATETIME NOT NULL,
	H_AMOUNT DECIMAL(6,2) NOT NULL,
	H_DATA VARCHAR(24) NOT NULL,
	FOREIGN KEY(H_C_W_ID, H_C_D_ID, H_C_ID) REFERENCES CUSTOMER(C_W_ID,C_D_ID,C_ID),
	FOREIGN KEY(H_W_ID,H_D_ID) REFERENCES DISTRICT(D_W_ID,D_ID));

CREATE TABLE IF NOT EXISTS `ORDER` (
  O_ID INT(11) NOT NULL,
  O_C_ID INT(11) NOT NULL,
  O_D_ID INT(11) NOT NULL,
  O_W_ID INT(11) NOT NULL,
  O_ENTRY_D DATETIME NOT NULL,
  O_CARRIER_ID INT(11) NOT NULL,
  O_OL_CNT DECIMAL(2,0) NOT NULL,
  O_ALL_LOCAL DECIMAL(1,0) NOT NULL,
  PRIMARY KEY(O_W_ID, O_D_ID, O_ID),
  FOREIGN KEY(O_W_ID, O_D_ID, O_C_ID) REFERENCES CUSTOMER(C_W_ID,C_D_ID,C_ID));

CREATE TABLE IF NOT EXISTS NEW_ORDER (
  NO_O_ID INT(11) NOT NULL,
  NO_D_ID INT(11) NOT NULL,
  NO_W_ID INT(11) NOT NULL,
  PRIMARY KEY(NO_W_ID, NO_D_ID, NO_O_ID),
  FOREIGN KEY(NO_W_ID, NO_D_ID, NO_O_ID) REFERENCES `ORDER`(O_W_ID, O_D_ID, O_ID));

CREATE TABLE IF NOT EXISTS STOCK (
  S_I_ID INT(11) NOT NULL,
  S_W_ID INT(11) NOT NULL,
  S_QUANTITY DECIMAL(4,0) NOT NULL,
  S_DIST_01 VARCHAR(24) NOT NULL,
  S_DIST_02 VARCHAR(24) NOT NULL,
  S_DIST_03 VARCHAR(24) NOT NULL,
  S_DIST_04 VARCHAR(24) NOT NULL,
  S_DIST_05 VARCHAR(24) NOT NULL,
  S_DIST_06 VARCHAR(24) NOT NULL,
  S_DIST_07 VARCHAR(24) NOT NULL,
  S_DIST_08 VARCHAR(24) NOT NULL,
  S_DIST_09 VARCHAR(24) NOT NULL,
  S_DIST_10 INT(24) NOT NULL,
  S_YTD DECIMAL(8,0) NOT NULL,
  S_ORDER_CNT DECIMAL(4,0) NOT NULL,
  S_REMOTE_CNT DECIMAL(4,0) NOT NULL,
  S_DATA VARCHAR(50) NOT NULL,
  PRIMARY KEY (S_W_ID, S_I_ID),
  FOREIGN KEY (S_W_ID) REFERENCES WAREHOUSE(W_ID),
  FOREIGN KEY (S_I_ID) REFERENCES ITEM(I_ID));


CREATE TABLE IF NOT EXISTS ORDER_LINE (
  OL_O_ID INT(11) NOT NULL,
  OL_D_ID INT(11) NOT NULL,
  OL_W_ID INT(11) NOT NULL,
  OL_NUMBER INT(11) NOT NULL,
  OL_I_ID INT(11) NOT NULL,
  OL_SUPPLY_W_ID INT(11) NOT NULL,
  OL_DELIVERY_D DATETIME NULL DEFAULT NULL,
  OL_QUANTITY DECIMAL(2,0) NOT NULL,
  OL_AMOUNT DECIMAL(6,2) NOT NULL,
  OL_DIST_INFO CHAR(24) NOT NULL,
  PRIMARY KEY(OL_W_ID, OL_D_ID, OL_O_ID, OL_NUMBER),
  FOREIGN KEY(OL_SUPPLY_W_ID, OL_I_ID) REFERENCES STOCK(S_W_ID, S_I_ID));



SELECT * FROM WAREHOUSE;

SELECT * FROM ITEM;

SELECT * FROM STOCK;

SELECT * FROM DISTRICT;

Select * from CUSTOMER;

Select * from `ORDER`;

Select * from NEW_ORDER;

Select * from ORDER_LINE;


